### ISSUE TITLE
Nginx-Reverse-Proxy-SSL support CONNECT method ?

### ISSUE THREAD

**Issue by ingnelson** [munnaeebd/Nginx-Reverse-Proxy-SSL#1]
Hello sir.

I would like your help and i am glad to pay you for your service.

1) I am behind a firewall

 2) The client is a Android Application, it can sends an HTTP request with the proxy and then to the SSH server to create the tunnel.

3) On the internet I found the following:
 HTTP proxy: 50.18.211.227:8043
 Fully qualified domain name (FQDN): 5ef50094901b6f5fccdfd0f6-172-245-22-211.cloudmi.datami.net

The proxy is linked to their domain, the only thing that altered was the domain which removed their IP that it had and put or added mine 172-245-22-211 so that your proxy will not reject the connection.

I show you the connection that WIRESHARK shows me. What you send and what you receive :

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)

It is possible to create a proxy that support CONNECT method and support HTTPS or SSL  like that proxy I found on the internet  ? 

The proxy 50.18.211.227:8043  response is :

HTTP/1.1 200 Connection established.
Server: sdgw

then goes the response from my SSH dropbear on port 443 and the tunnel is created.

i want a proxy like that on my VPS .

I am going to wait for your reply.

**Comment by munnaeebd** [comment]
Hi,

If the solution is required for only SSH connection. You can think the solution differently.  I have the below idea. 

Client-->Proxy-server-->Destination-host
Client will send request to proxy-server using assigned port(like: 5555) --> proxy server send this request to destination host in 22 port or any other port. destination server will send public certificate for encryption . after the encryption phase complete, encrypted data will transfer. 

following command on proxy server:
~~~
ssh -v -fNL 0.0.0.0:5555:destination-host:22 root@proxy-server
~~~
Then send any request to proxy server with 5555 port it will forward to destination host with 22

If you need solution differently (like:reverse-proxy). Let me know, I will think again.

**Comment by ingnelson** [comment]
I really like that option that said . If i send you my VPS , my user name and password , could you install it on my VPS the proxy and redirect to the ssh.

**Comment by munnaeebd** [comment]
Its just e command, if u have linux machine,  this command should run and hopefully you can get your desired service

**Comment by ingnelson** [comment]
@munnaeebd here is my:

```
Ubuntu VPS : 172.245.22.211
User: root
Password : ******
Domain : datami.ssl.zteclaro.tk
```

Can you install the proxy on 0.0.0.0 5555 and redirect to my the ssh dropbear that is listening on 0.0.0.0:442 , please . Because I am not so good using Linux Please .

So this way I can use the http injector app on android as a client send the http request :

`CONNECT datami.ssl.zteclaro.tk:442 HTTP/1.0\r\n\r\n`

Using the proxy : 172.245.22.211:5555

![IMG_20200703_133431](https://user-images.githubusercontent.com/6626845/86494394-2e3d3880-bd32-11ea-993a-c41825e045d0.jpg)
![IMG_20200703_133412](https://user-images.githubusercontent.com/6626845/86494395-2f6e6580-bd32-11ea-813a-f16ecda2b709.jpg)

**Comment by munnaeebd** [comment]
Please do not provide password in any public place,  I just hide it. Ok, its midnight here, I will check in morning and let you know the update

**Comment by munnaeebd** [comment]
Please check now if you can access your service

**Comment by munnaeebd** [comment]
This solution is like port forwarding. There is more solution available depend on your application or use case.  like: Nginx Reverse proxy, or squid proxy

**Comment by ingnelson** [comment]
@munnaeebd on what port did you install the proxy ? What port is listening the proxy server ?

**Comment by munnaeebd** [comment]
port: 5555

172.245.22.211:5555 -->> datami.ssl.zteclaro.tk:442

**Comment by ingnelson** [comment]
@munnaeebd there is not a port listening on 0.0.0.0:5555 when I use the command : 
`netstat -tulpn`

And if I try to connect my Android via the proxy 172.245.22.211:5555 

![Screenshot_2020-07-04-10-23-53-259_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/86516852-4c15a680-bde1-11ea-89f3-1a643e76738e.jpg)


Look that there is not a listening proxy or there is not a connection .

Install http injector app on your Android phone:
https://play.google.com/store/apps/details?id=com.evozi.injector

 and unzip then import this configuration on the http injector app:

[test.ehi.zip](https://github.com/munnaeebd/Nginx-Reverse-Proxy-SSL/files/4873221/test.ehi.zip)



please to check it and the vps and you will see the proxy it is not listing on 0.0.0.0:5555

**Comment by munnaeebd** [comment]
Please check now, 

root@TameValid-VM:~# netstat -tulnp | grep 5555
tcp        0      0 172.245.22.211:5555     0.0.0.0:*               LISTEN      4484/ssh

**Comment by munnaeebd** [comment]
Hi, 

is it worked? or you find another solution.
